### ISSUE TITLE
Managing broken connection & Connection best practices

### ISSUE THREAD

**Issue by muhamad-ahsan** [Azure/azure-service-bus#14]
@jtaubensee could not find the stuff related to manage the broken connections. Please share some practice related to this concern (how to reconnect, events that should be attached to monitor etc.)...

**Comment by jtaubensee** [comment]
@muhamadahsan - Can you be a little bit more specific about what you are looking for? Also what client are you using?

**Comment by muhamadahsan** [comment]
I am using "WindowsAzure.ServiceBus" version "3.4.6". For the scenario, I am looking for a long running task (maybe the background the thread or process) waiting for the messages to be sent to queue. I am not disposing the queue client throughout the life cycle of the process. But after some time, the connection will be closed from the Azure ServiceBus side and I need to reconnect before sending. So, my concern is, if there is any way to make sure that connection will be auto reconnected? Or if the connection goes down because of network issue or any other thing, how will it resolved? Any events which can be attached to the queue client for connection failed etc.?

**Comment by jtaubensee** [comment]
@muhamadahsan - Are you receiving any particular errors? We have a default retry policy that should handle transient connection errors.

**Comment by muhamad-ahsan** [comment]
I am not getting any particular error. I was wondering if there is any event I can attached to monitor the connection life time or behavior. E.g. event on connection reconnected, connection broken etc.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
