### ISSUE TITLE
SqlRuleAction is not sufficiently documented

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#180]
[Documentaiton](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-sql-rule-action) doesn't provide sufficient information about what can be done with rule actions.
The only documented functions are `newid()` and `property()`. And even these appear in remarks.

It should address questions such as
- What properties can it modify on what entities
- How to set values that are not `string` (datetime, boolean, numeric)

**Comment by EldertGrootenboer** [comment]
We have added this to the backlog, and will update this issue when we have more information.

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback. We have brought this item in our current semester, and should be able to provide an update in the coming months.

**Comment by yvgopal** [comment]
We will update the documentation.
1. Only properties on a message can be modified. All user properties can be modified. All publicly settable system properties can also be modified, like ReplyTo, CorreationId... But we recommend not altering system properties as part of a rule action. We are not disabling it for backward compatibility reasons.
2. When setting properties, only numeric, Boolean and string literals are allowed. A string literal in turn will be converted to a type based on the property being modified. If the property being set doesn't already exist, there is no type conversion from string. If the property being modified already exists and its value is one of these types Guid, DateTimeOffset, TimeSpan, Uri, DateTime, then the string literal will be converted to that type and set as the property value. To be more specific, the action tries to convert the string literal to the type of property. If it is successful, the property will be set. Otherwise rule action evaluation throws an exception and the message will be dead-lettered.

**Comment by EldertGrootenboer** [comment]
The documentation changes are live now, closing this issue.
