### ISSUE TITLE
Receiving batch of messages in IMessageHandler

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#205]
# Description
Greetings,
In my application I send messages by using batches, Azure Service Bus SDK allows to send batch of messages and it helps to reduce the number of requests to a queue or a topic. 

```
  private void sendBatch(List<Message> commandBatch) {
        val queueClient = this.commandSendClientPool.sendClient();
        queueClient.sendBatchAsync(commandBatch).exceptionally(throwable -> {
            if (throwable instanceof ServerBusyException) {
                log.warn("SERVICE IS BUSY. WAIT 5 SECONDS");
            }
            val messagesIds = commandBatch.stream().map(Message::getMessageId).collect(Collectors.toList());
            log.warn("BATCH OF COMMANDS {} CANNOT BE PROCESSED, will be recent one more time", messagesIds);
            return null;
        });
    }
```

It works find, but I would like to have a chance to receive batches of messages on consumer side. For the moment handler API does not allow to do this.

```
@Slf4j
@RequiredArgsConstructor
public class EventsHandler implements IMessageHandler {
    ....
    @Override
    public CompletableFuture<Void> onMessageAsync(IMessage message) {
        log.debug("Event has been received and complete, message id is {}", message.getMessageId()); 
        ...
    }
```
# Question

Do you have any suggestions how can I implement receiving batches of messages on consumer side? Is it planned to have in next versions of SDK?

**Comment by nemakam** [comment]
AMQP is a streaming protocol, and doesn't work great with batches. We are working on this known problem to improve the efficiency, but as of now all the receives get one message only. 

The API you are looking for is `messageReceiver.receiveBatch()`. That method currently batches messages that are streamed. You could use that if you need better control over batching. But providing batching support in `IMessageHandler` interface would be unlikely. That is since, prefetching the messages should remove most of the overhead of batching.
