### ISSUE TITLE
Cancelling a message with an incorrect sequence number returns a misleading error message

### ISSUE THREAD

**Issue by gmacster** [Azure/azure-service-bus#239]
# Description

## Actual Behavior

An inaccurate and misleading error message is returned from the Service Bus service when calling `TopicClient.CancelScheduledMessageAsync(long sequenceNumber)` for non-existent sequence numbers in certain cases (especially with longer numbers). This is reproducible from both the .NET and Java client libraries which leads me to believe this is a server-side problem.

| Sequence Number | Actual Error Message |
| - | - |
| 10696049115006452L | Messages not found. Missing sequence numbers: 1524 |
| 1069604911500645L | Messages not found. Missing sequence numbers: -56294995341979 |
| 106960491150064L | Messages not found. Missing sequence numbers: 106960491150064 |

## Expected Behavior

The error message should contain the actual sequence number that was passed into the `CancelScheduledMessageAsync` call:

| Sequence Number | Expected Error Message |
| - | - |
| 10696049115006452L | Messages not found. Missing sequence numbers: 10696049115006452 |
| 1069604911500645L | Messages not found. Missing sequence numbers: 1069604911500645 |
| 106960491150064L | Messages not found. Missing sequence numbers: 106960491150064 |

**Comment by axisc** [comment]
Thanks for reporting this. we will investigate server side.

**Comment by gmacster** [comment]
Here's a Java sample using `com.microsoft.azure:azure-servicebus:1.2.8`: https://github.com/gmacster/ServiceBus-Cancellation-Testing-Java

**Comment by yvgopal** [comment]
Thanks for providing the sample. I reproduced it. It is caused by a missing validation in the service. It happens only with partitioned queues/topics.
The sequence number you are sending is just a random long, and service bus will never generate it. 
The service bus internally pads some bits to the sequence number to identify which partition it has come from. As you are sending a random long, the padding info taken from it is mostly garbage. In some cases, as in your sample, the padding info coming from the random long actually maps to a partition, but still there is no message with the sequence number in the partition. Even to re-generate the exact sequence number back, we need the padding info. The service doesn't pass the padding info along across components, so regenerating the sequence number for the error message needs many tweaks.

Instead I just tweaked the error message to not include a sequence number in it. This is a simple fix, to address a corner case. So I didn't do the elaborate fix of passing the padding info everywhere.

**Comment by gmacster** [comment]
Thanks for taking a look, removing the number from the log statement will help.

For the record, that `10696049115006452` number _was_ a real example of a sequence number our Service Bus instance generated. Not just a "random" long.

**Comment by Nlouis00** [comment]
Hi, the SequenceNumber I get from the service Bus is also very long and is confusing. I would expect some type of counter but get some number that seems random (although when I recreate the queue, I get the same number over and over). Here are a few example:
0000000000000016
0000000000000032
0000000000000048
0000000000000064
0000000000000080
0000000000000096
0281474976710657
0281474976710673
0281474976710689
0281474976710705
0281474976710721
some explanation about how the sequence number is generated would help.
Thank you
Nicolas

**Comment by yvgopal** [comment]
For a non-partitioned entity, sequence number starts at 1 and is incremented for every message. For a partitioned entity, there are multiple partitions internally and sequence number starts at 1 for each partition. So we pad some extra bits to the sequence number to identify the partition. So what you see as sequence number for a partitioned entity is partitioninfo + sequencenumber. That is why when you use random long number as sequence number in a complete or renew request, service bus cannon determine the partition from it.

**Comment by Nlouis00** [comment]
Hi,
Is there an easy to separate the partitionId from the actual seq number? I turned off partition and it looks perfect. It would be convenient to be able to get those seq number even in a partitioned service bus. Can we pad the seq number with 0 and get the partitionid in front? 123456780000001 etc....
Thank you for your help.
Nicolas
