### ISSUE TITLE
ServiceBusTrigger does not trigger on consumption plan with Managed Identity

### ISSUE THREAD

**Issue by KristofC4T** [Azure/azure-service-bus#337]
# Description
I'm having a problem in the following combination:
- function app on a consumption plan
- function with ServiceBusTrigger
- connection string to the service bus in app settings, looks like "Endpoint=sb://xxxxx.servicebus.windows.net;Authentication=Managed Identity;"
- on the SB, the function app has 'Azure Service Bus Data Receiver' and 'Azure Service Bus Data Sender' rights
- message is waiting on service bus topic
- function app is deployed using Azure App Service deploy task on Azure DevOps

## Actual Behavior
message is not picked up by function app 

## Expected Behavior
message remains on topic

## Additional info
Only when the function app is accessed in the azure portal will it become active and pick up the message. Another message placed on the queue right after is also processed. After letting it idle for an hour and placing another message on the queue, it is not picked up until someone accessed the app through the portal.

Granting Owner rights on the SB for the function app did not resolve, choosing different deployment methods in the Azure App Service deploy task did not resolve.
Only when the connectionstring was altered to use a SAS token, did it work as expected that messages got picked up right after deploy and after idle time.

Microsoft.Azure.WebJobs.Extensions.ServiceBus Version="4.1.0"
Microsoft.NET.Sdk.Functions Version="3.0.3"

Edit: also tried removing the semicolon at the end of the connection string, as was suggested here: https://github.com/Azure/azure-functions-host/issues/3966#issuecomment-464242142
Did not resolve the issue.

**Comment by SeanFeldman** [comment]
This issue is unlikely to belong here, @KristofC4T. This specific repository is for the broker issue tracker. Please review [README.md](https://github.com/Azure/azure-service-bus#microsoft-azure-service-bus).

Specifically, about this issue, the repository you can raise this issue is https://github.com/Azure/azure-functions-servicebus-extension/. There was a conversation about Managed Identity and Service Bus trigger on consumption plan, with some limitations that could cause scale-out problems. Suggest you raise the issue in the appropriate repo to get the attention of the correct team and get some answers. Good luck.

**Comment by KristofC4T** [comment]
Moving issue to other repo
