### ISSUE TITLE
Peeking and cancelling messages from a topic

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#352]
The idea of an ASB topic to be send-only entity. The underlying implementation of a topic seems to be leaking out. It's possible to **peek** and **cancel** messages in the topic when either one of the conditions is fulfilled:

1. A message is scheduled and the time hasn't elapsed yet.
1. The topic has a high load and the processing subscription is slow to consume the messages.

In those scenarios, messages in the topic can be peeked and cancelled by their sequence number. Unlike the **receive** operation, which is explicitly blocked (throws `MessagingEntityNotFoundException`).

Given the send-only nature of topics, should this behaviour be allowed?
Or would this be considered a deviation and be patched?

**Comment by axisc** [comment]
@SeanFeldman Thanks for reporting this. I agree that this looks suspect, but we will investigate this to understand if there was some reason to allow this operation in the past and revisit appropriately. 

I'm tagging this as a possible `bug`

**Comment by patrickgalbraith** [comment]
@axisc Did you get a chance to have a look at this?

**Comment by EldertGrootenboer** [comment]
This is not a deviation, but by design. 

1. For scheduled messages this is the only way to see which scheduled messages are on a topic, as they only become visible on their corresponding subscriptions after the scheduled time has elapsed.
2. When messages have not been delivered to their corresponding subscriptions yet, this behavior allows identifying which messages are being blocked.
