### ISSUE TITLE
New SubQueue - Invalid Message

### ISSUE THREAD

**Issue by preardon** [Azure/azure-service-bus#466]
At the minute (According to the documentation) the following sub Queues Exist

- None (the main queue)
- DeadLetter (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq)
- TransferDeadLetter - For certain scenarios to do with issues Chaining messages

I would like an Extra Sub Queue added for Malformed or Invalid messages, in the short term I would like the ability a Service Bus Receiver to be able to send messages that it considers malformed into this queue so that they can be managed separately to messages that cannot be delivered (DLQ)

In the future I can see things like a Json Schema Validator being used to Automatically send messages to this queue however I feel that this is out of scope for this request

**Comment by SeanFeldman** [comment]
> I would like an Extra Sub Queue added for Malformed or Invalid messages; in the short term, I would like the ability of a Service Bus Receiver to be able to send messages that it considers malformed into this queue so that they can be managed separately to messages that cannot be delivered (DLQ)

Unlike MSQM, a dead-letter queue is not intended solely for messages that cannot be delivered. On the contrary, it is designed to collect messages that are poisonous, malformed or failed processing multiple times due to a logical problem (a but in the processor, etc.) When a message cannot be ingested, it can be dead-lettered explicitly rather than rely on multiple retries. That is a problem as a single queue, DLQ, is overloaded with responsibilities. Middleware frameworks such as [NServiceBus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/build-message-driven-apps-nservicebus?) provide an additional queue, an error queue, that is used for messages that are valid and failing processing, where malformed messages are moved to the DLQ as re-processing those doesn't help.

There's an [Azure Schema Registry for Azure Event Hubs](https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview). Sounds like what you'd like would be related to this concept.

**Comment by EldertGrootenboer** [comment]
We will not add additional sub queues for this. These messages will be moved to the DLQ with a dead-letter reason, from where they can be processed accordingly.
