### ISSUE TITLE
Feature request: enable use of Private Endpoints for a standard tier of Service Bus

### ISSUE THREAD

**Issue by chudytom** [Azure/azure-service-bus#474]
# Description
For most use cases, Standard tier of Service Bus is just enough. All the capabilities of the Premium tier are not always needed. However if you want to enable secure access to a Service Bus using Microsoft backbone network using Private Endpoints, you have to migrate your Service Bus to a Premium tier. However the Premium tier seems to be even 60 times more expensive for basic use cases 
![image](https://user-images.githubusercontent.com/29259905/171655465-52d448da-f7eb-4bf6-b375-735ea3ab4c1b.png)

-->

## Actual Behavior
1. Currently in order to be secure and implement Private Endpoints we need to migrate to the Premium Tier of Service Bus. It's been even mentioned in the documentation https://docs.microsoft.com/en-us/azure/service-bus-messaging/private-link-service#important-points

## Expected Behavior
1. Enable the use of Private Endpoints in the Standard tier of Service Bus

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback. However, we are not planning to bring this feature to the Standard tier, due to the internal constraints of our architecture. For advanced networking scenarios, such as integration with VNET, we recommend going to the premium tier.

**Comment by chudytom** [comment]
@EldertGrootenboer have you considered sth in between? Some capabilities of the Premium tier but with the pricing that isn't 60 times more expensive. In our case at least it means that we will need to replace it e.g. with Kafka. Right now the Premium Service Bus seems simply too expensive

**Comment by EldertGrootenboer** [comment]
@chudytom We are looking into options for bridging the pricing gap between Standard and Premium, but we don't have more details to share yet.

**Comment by chudytom** [comment]
@EldertGrootenboer sounds promising. Thank you for the update. Any rough timeline when we can expect more updates?

**Comment by EldertGrootenboer** [comment]
No specific timelines yet, except that this is in active development.

**Comment by SeanFeldman** [comment]
> No specific timelines yet, except that this is in active development.

In that case the issue should remain opened until the work is completed.

**Comment by chudytom** [comment]
@EldertGrootenboer I agree with Sean. Can we repoen the issue?

**Comment by EldertGrootenboer** [comment]
Reopened, although important to note that this is not to track enabling private endpoint on standard tier, but for an alternative to bridge the pricing gap.

**Comment by epomatti** [comment]
@EldertGrootenboer giving how much messaging is central to todays' architecture and the high stakes regarding current Cyber Security audit and assessments, this is a huge turn off from small to even large-ish projects.

I've been consulting for several startups and the decision is simply to not use Service Bus. Security will take the lead on this one. They prefer to run a RabbitMQ VM than to expose their data to the internet.

How are Solution Architects supposed to sign-off a project design that is either overly expensive, or inherently insecure?

Other services, even with Basic tier, enable private endpoints, such as App Services and SQL Database.

"Public Access" is a big no no.

![image](https://user-images.githubusercontent.com/6530769/194725586-3fa95840-556b-4083-b8a5-d4eff0b0d433.png)

**Comment by si-te** [comment]
The absense of private endpoints for the standard tier is even further problematic, since there is no built-in firewall for the public endpoint, as there is for example with storage accounts or other managed services. This makes the standard tier really only rely on authentication for access control. And even there SAS Tokens (which are required for some usecases) are problematic since they are not bound to an identity provider such as AAD. 

Maybe adding an integrated firewall for the public endpoint of standard tier similar to storage accounts would be an acceptable middleground?

**Comment by chudytom** [comment]
@EldertGrootenboer do we have any progress on bridging the option on Standard vs the Premium tier of Service Bus. It's been over a year since we had some information about the progress

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback on this item. We are currently actively investigating the possibilities around this feature, however we currently don't have an ETA on when development might start on this. We encourage everyone to share the scenarios where they would like to use this feature, to help us shape it in the best way.

**Comment by EldertGrootenboer** [comment]
This feature in our backlog, however we currently don't have an ETA on when development might start on this. For now, to help us give this the right priority, it would be helpful to see others vote and support this feature, as well as explain their scenarios.

**Comment by zyofeng** [comment]
I would strongly vote for this feature.
Most of our Azure infrastructure, including SQL, storage accounts, Cosmos DB, and Key Vault, is secured behind VNets and private endpoints. 

However, one critical component still missing this is the Service Bus, which is a key element of our service communication backbone, we don't need any other features in the premium tier.

**Comment by vpshibin** [comment]
Strongly support/vote this feature.

Our Enterprise Security only allows Private endpoint access for Service Bus (and similar PaaS services). And the use cases mostly only need a Standard tier (at least in NonProd). It doesn't make sense to pay 60 times cost for Premium just for the Private endpoint feature.

**Comment by wolszakp** [comment]
Any updates about that?
We are waiting for this feature.

**Comment by EldertGrootenboer** [comment]
There are currently no further updates to share around this. For now, we recommend to keep upvoting this item and sharing your scenarios, and we will keep this thread updated if we have an update to share around this.

**Comment by timonmat** [comment]
Using the Azure Enterprise Landing Zone model, and recommended isolation of LZ's per system, it becomes mandatory to have  premium tier service bus for each individual application (when following DevOps models where we try to decrease the amount of shared company managed services in use and keep the DevOps team in control of their services). Large enterprises, like us, in regulated industries are not allowed to expose public uncontrolled endpoints at all.
Most applications, out of hundreds, do not require the scale of even the smallest premium tier. some do, but most don't. So it very often becomes impossible to justify using service bus at all when it does not have private endpoint support for small scale usage.
Private endpoint support for variable pricing models (similarly to flex capacity coming to azure functions) would increase our ability to migrate to azure cloud faster and decrease refactoring costs.

**Comment by andyamacdonald** [comment]
To echo all of the above this is a critical feature for us either as an addition to the standard tier or as part of a new intermediate tier. 

The price jump from standard to premium is massive especially considering the only feature we currently need is private endpoints.

**Comment by DavidPriceNBS** [comment]
Since it's approaching 3 years since this limitation was initially brought up, I was curious if there is any update? 

As others have mentioned the leap from Standard to Premium in pricing is gigantic when the only feature required is private endpoints, a feature offered on most other services without the need for the highest tier. It feels excessive to go from a flat rate of ~£8 to ~£530 to secure an endpoint as per recommended best practices and certainly for ourselves a price that is difficult to justify to stakeholders, thanks.

**Comment by EldertGrootenboer** [comment]
We are looking into options around this, however this is in an early investigation stage still. Currently there are no timelines to share around if and when we might have more information on this. We do value the feedback and would recommend continuing providing feedback and the scenarios where you mostly run into this.

**Comment by cwe1ss** [comment]
It's great to hear that you're thinking about this. But since this seems like a very straight-forward request (which might of course be hard to implement for you) that's already supported by many/most other Azure services, I'm wondering what kind of additional feedback/scenarios, other than upvotes, would be of help? I'd be happy to discuss this with our colleagues & clients if you need some specific information.

**Comment by brad-dawson** [comment]
@EldertGrootenboer our use case would greatly benefit from a standard pricing tier that allows for the use of private endpoints. Since we run Azure Virtual Gateways into our Hub & Spoke topology, we have lots of PEPs to allow for secure connections for point to site into Azure. We also have some needs to allow for cross hub integration, so being able to place a PEP into another network hub's is ideal.

**Comment by Vipersoft-01** [comment]
@EldertGrootenboer  We’ve run into the exact same challenges mentioned here, so I wanted to share our perspective as well.

We currently maintain three environments (DEV, TST, and PROD). The lack of a true “Development” tier (similar to what APIM provides, including VNET support) is a real pain point.

As a direct consequence, we’re forced to provision Premium in DEV and TST just to deploy and validate our configurations properly. That results in a fixed extra cost of roughly €1,200 per month for non-production workloads — cost that doesn’t really add value, but is necessary to test realistically.

A stripped-down “Development” or “Non-critical workload” tier would make a huge difference for teams like ours.

**Comment by TheAzureGuy** [comment]
One more vote for private endpoint support in ASB Standard SKU. Having major difficulties justifying the use of Premium SKU to my leadership team just to maintain the basic level of security compliance. It gets to a point where I'm being asked to look for an alternative solution (replace SB with something else) or even another cloud platform provider. I get all these "internal architecture limitations" but at some point, security common sense should prevail and Microsoft should absolutely encourage clients to build secure solutions by offering basic security features in lower tier SKUs.

**Comment by chudytom** [comment]
It's almost 4 years since I raised this issue and in fact Microsoft makes no progress about it.
Internally, we switched to Kafka from Confluent as an alternative

**Comment by DavidPriceNBS** [comment]
Unfortunately due to the lack of attention this receives we've had to migrate from service bus, I really do believe there needs to be some kind of intermediate compromise tier for those who require private networking from a compliance standpoint, but also can't justify to stakeholders a £550 fee for the uplift.

In fact we've had to re-architecture our entire system due to this and move away from other managed Azure services such as container apps since we're now hosting our own RabbitMQ.

A real shame this isn't taken more seriously by MS after 4 years when private endpoints are such a core part of every other service offering without having to increase your billing model x50.

**Comment by cencristian** [comment]
Sharing an update that might be useful for everyone following this issue.

I opened a formal support ticket with Microsoft as an EA customer and asked them to escalate to the Service Bus product group specifically about this. After the escalation, I got written confirmation from a Microsoft Azure Support Engineer:

> There are currently no plans to introduce Private Endpoint support for Azure Service Bus Standard tier.
> There are currently no plans to introduce VNet Service Endpoint support for Azure Service Bus Standard tier.
> This limitation is due to architectural differences between the Standard and Premium tiers, and as a result, certain Premium features cannot be extended to Standard.
> The request for enabling these capabilities in Standard tier has been acknowledged by the Product Group and is being tracked as a feature request for future consideration.
> At this time, there is no public documentation or roadmap commitment that explicitly confirms future availability of these features in Standard tier.
> This confirmation can be used for internal documentation and policy exception justification.

So after three years of "in active development, no ETA", the actual answer from the product group is: no plans.

I also asked specifically about VNet Service Endpoints as a lighter alternative. Same answer.

For some context on why this matters at scale: our tenant has 560 Service Bus namespaces. 380 of them are Standard or Basic with no path to Private Endpoint compliance. Upgrading all of them to Premium 1MU just to satisfy a network isolation policy would cost around $3.1M/year. None of those workloads actually need Premium features, the only driver would be the compliance requirement.

For anyone blocked by this today, the realistic options are:

1. Upgrade to Premium if you also need other Premium features and can justify the cost
2. Keep policy exemptions and use this confirmation as the justification
3. Migrate to Storage Queues where the use case allows, since those support Private Endpoints at any tier
4. Self-hosted broker inside your VNet if cost is a hard constraint

Hope this helps others make a decision and stop waiting.
