### ISSUE TITLE
MaxMessageBatchSize Service bus queue - question

### ISSUE THREAD

**Issue by lugospod** [Azure/azure-service-bus#569]
Trying to find out how batching works between Service bus queue and Azure functions.
Azure function has IsBatched property and Service Bus Queue has MaxMessageBatchSize property.
_The maximum number of messages that will be passed to each function call. This setting only applies for functions that receive a batch of messages._

But there is no information on how does this process work. **How much time does service bus queue wait for MaxMessageBatchSize of messages to be created before triggering the function with array of messages as parameter? How do we set this timeout?**

I would like to avoid calling the function for each message, but would like to have the flexibility to define how long the queue is allowed to wait before notifying me about messages that were received so far (up-to MaxMessageBatchSize).

Tnx!
Luka

**Comment by SeanFeldman** [comment]
`IsBatched` is a Functions ASB trigger **flag** to indicate messages should be received in batches rather than one at a time. `MaxMessageBatchSize` is a Functions option to indicate the maximum **number of messages** that will be passed to each function call.

> How much time does service bus queue wait for MaxMessageBatchSize of messages to be created before triggering the function with array of messages as parameter? 

The ASB SDK, used to implement Functions ASB trigger doesn't wait for that exact number of messages. This number indicates how many messages will be sent down to the function **_at-most_**. The server will provide whatever it has.

This repo has nothing to do with Functions SDK or any other client SDK as it's about server side. But it does influence every other SDK using it. Given this is how ASB works when it comes to receiving batched messages, you are not guaranteed to receive exactly the batch size you're requesting.

**Comment by lugospod** [comment]
Thank you very much @SeanFeldman for a speedy response!
