### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by dee-cf** [Azure/azure-service-bus#720]
On this page 
https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-counters

docs say:

`If an application wants to scale resources based on the length of the queue, it should do so with a measured pace. The acquisition of the message counters is an expensive operation inside the message broker, and executing it frequently directly and adversely impacts the entity performance.`

Is there any quantification of that statement? What is the measured way? What is too much? What is reasonable?
Just as an order of magnitude clarification would be very useful.

**Comment by EldertGrootenboer** [comment]
There are no explicit recommendations, as it all depends on the rest of your environment. In general, we would recommend getting the counters not more than once a minute, however this is not a hard limit. Depending on the throughput of your workloads, size of the messages, use of features, etc., your solution might have plenty of resources available, or already be low on resources. In general, this statement is meant as a guidance to prevent slowdown of your workloads due to behavior which might not explicitly be useful for your scenario.
