### ISSUE TITLE
Ability to generate and set the subscription name (UUID) explicitly

### ISSUE THREAD

**Issue by dasjestyr** [Azure/azure-service-bus#96]
# Description

## Actual Behavior
1. Right now, long subscription names are replaced with a UUID, and this property is restricted to 50 characters. This limits the ability of managed service bus implementations such as NServiceBus.

## Expected Behavior
1. I believe it could be a useful compromise to allow the subscription name to be set explicitly, but in order to achieve this, it may be necessary to provide a way to calculate the UUID using the same method being used by Azure. So for example, if I am the ASB SDK for NSB, I can then use the generator to get the UUID, then map this UUID to my subscription name and serialize it along with my message. This way, the 50 character limit can be honored, but still allow me to give a much longer subscriptions name (typically the FQN class name of the message so that I can pair it with the correct handler).  This may have broker implications but would definitely need to be a function provided by the ASB client library which is currently being rewritten for .net standard.

**Comment by nemakam** [comment]
> Right now, long subscription names are replaced with a UUID

@dasjestyr This is not something that is currently done by the ASB SDK. Maybe it is done by NSB? Current ASB client just throws `ArgumentOutOfRangeException` when subscription name is greater than 50 chars.
@SeanFeldman , do you have any idea here?

**Comment by SeanFeldman** [comment]
I think what @dasjestyr is asking is to provide a deterministic shortener for 3rd parties to leverage. I.e., when someone is using a subscription name that exceeds the maximum length, rather than each 3rd party create their own shortening algorithm, they'd leverage a single one provided by the ASB client.

What NSB is doing today shortening those names using customer provided algorithm.

**Comment by nemakam** [comment]
If I read it correctly, this is a request to basically remove the limitation of 50 chars for names (by using any possible implementation; one of which is suggested in the original post)?

**Comment by SeanFeldman** [comment]
I'd say all entities, not just subscriptions.

**Comment by nemakam** [comment]
@dasjestyr @SeanFeldman 
The entity can itself store some [user metadata](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.usermetadata?view=azureservicebus-4.1.1#Microsoft_ServiceBus_Messaging_SubscriptionDescription_UserMetadata). You could use this to your advantage if you don't mind the additional call.

**Comment by SeanFeldman** [comment]
@nemakam that's indeed what NServiceBus is doing.
I guess what @dasjestyr is after is rather than "shortening" being done by a 3rd party like NServiceBus, it would be done by the client.

**Comment by nemakam** [comment]
I don't see the advantage of doing this in ASB client. If we end up using the same logic of storing the full name in user-metadata, then the client will have to do the same call which can be done by third party (like NServiceBus). If we talk about consistent approach across different 3rd parties, it shouldn't really matter as any short name generation should suffice here. Any hash algorithm of the name should work. If we do it in the ASB client, that is exactly what it will also end up doing. 
IMO, this doesn't look like a generic enough scenario that applies to everyone. Also, doing this in client will end up making it more complicated for majority of folks who wouldn't need this feature. There would also be further complications of logging / support etc since service would only have the short name and wouldn't really have the long name (and assuming that the hash is not reversible). Making such hacks inside the SDK doesn't really look right to me.
